training: !!bool "true"
device: "cuda"

---
data:
    dataset: './data_kimura_10words'
    train_path: './train_tisv'
    test_path: './test_tisv'
    test_path_unprocessed: './TIMIT/TEST/*/*/*.wav'
    data_preprocessed: !!bool "true"
    embedding_path: '/emb'
---   
model:
    num_res: 5 #Number of stcnn layers
    res_layer: 2 #Num of res-block
    proj: 512 #Embedding size
    model_path: './model.model' #Model path for testing, inference, or resuming training
---
train:
    N : 4 #Number of speakers in batch
    M : 5 #Number of utterances per speaker
    num_workers: 0 #number of workers for dataloader
    lr: 0.01
    cont_loss: 0.3
    epochs: 1200 #Max training speaker epoch 
    log_interval: 1 #Epochs before printing progress
    log_file: './speech_id_checkpoint/Stats'
    checkpoint_interval: 120 #Save model after x speaker epochs
    checkpoint_dir: './speech_id_checkpoint'
    restore: !!bool "false" #Resume training from previous model path
---
test:
    N : 4 #Number of speakers in batch
    M : 6 #Number of utterances per speaker
    num_workers: 0 #number of workers for data laoder
    epochs: 10 #testing speaker epochs
